"""tabla de concentrado de usuarios

Revision ID: 1c89cb655f49
Revises: 94378463e958
Create Date: 2026-04-29 18:47:50.901457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c89cb655f49'
down_revision: Union[str, None] = '94378463e958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concentration_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_employed', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('plataform', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id_user_create', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concentration_user_id'), 'concentration_user', ['id'], unique=False)
    op.create_index(op.f('ix_concentration_user_id_employed'), 'concentration_user', ['id_employed'], unique=False)
    op.create_index(op.f('ix_concentration_user_username'), 'concentration_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concentration_user_username'), table_name='concentration_user')
    op.drop_index(op.f('ix_concentration_user_id_employed'), table_name='concentration_user')
    op.drop_index(op.f('ix_concentration_user_id'), table_name='concentration_user')
    op.drop_table('concentration_user')
    # ### end Alembic commands ###
