"""agregar en los datos de empleado el numeor de empleado

Revision ID: 2316f394482a
Revises: 34df56a815ad
Create Date: 2026-04-28 12:04:07.954324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2316f394482a'
down_revision: Union[str, None] = '34df56a815ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_users', sa.Column('id_employed', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_data_users_id_employed'), 'data_users', ['id_employed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_users_id_employed'), table_name='data_users')
    op.drop_column('data_users', 'id_employed')
    # ### end Alembic commands ###
