"""cambio de usuarios y roles

Revision ID: 34df56a815ad
Revises: 7b3956077176
Create Date: 2026-04-27 18:06:30.866412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34df56a815ad'
down_revision: Union[str, None] = '7b3956077176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    role_enum = sa.Enum('admin_develop', 'coordinador', 'supervisor', 'calidad', 'administrativo', name='internaluserrole')
    role_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_internal_campaign_id'), 'internal_campaign', ['id'], unique=False)
    
    op.add_column('internal_users', sa.Column('role', role_enum, nullable=True))
    
    op.execute("UPDATE internal_users SET role = 'administrativo' WHERE role IS NULL")
    
    op.alter_column('internal_users', 'role', nullable=False)
    op.add_column('internal_users', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'internal_users', 'internal_campaign', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internal_users', type_='foreignkey')
    op.drop_column('internal_users', 'campaign_id')
    op.drop_column('internal_users', 'role')
    op.drop_index(op.f('ix_internal_campaign_id'), table_name='internal_campaign')
    op.drop_table('internal_campaign')
    # ### end Alembic commands ###
