"""Agregar logs peticiones y login y relaciones

Revision ID: 5cc3f4b7166c
Revises: 57de2d0d225d
Create Date: 2026-04-29 11:54:11.070559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc3f4b7166c'
down_revision: Union[str, None] = '57de2d0d225d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('path_requests', sa.String(), nullable=False),
    sa.Column('type_requests', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['internal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_requests_id'), 'log_requests', ['id'], unique=False)
    op.create_index(op.f('ix_log_requests_id_user'), 'log_requests', ['id_user'], unique=False)
    op.create_table('log_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['internal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_sessions_id'), 'log_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_log_sessions_id_user'), 'log_sessions', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_sessions_id_user'), table_name='log_sessions')
    op.drop_index(op.f('ix_log_sessions_id'), table_name='log_sessions')
    op.drop_table('log_sessions')
    op.drop_index(op.f('ix_log_requests_id_user'), table_name='log_requests')
    op.drop_index(op.f('ix_log_requests_id'), table_name='log_requests')
    op.drop_table('log_requests')
    # ### end Alembic commands ###
