"""crear tablas iniciales

Revision ID: 7b3956077176
Revises: 
Create Date: 2026-04-21 15:40:15.014671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3956077176'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_users_email'), 'internal_users', ['email'], unique=True)
    op.create_index(op.f('ix_internal_users_id'), 'internal_users', ['id'], unique=False)
    op.create_index(op.f('ix_internal_users_username'), 'internal_users', ['username'], unique=True)
    op.create_table('data_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['internal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_users_id'), 'data_users', ['id'], unique=False)
    op.create_index(op.f('ix_data_users_last_name'), 'data_users', ['last_name'], unique=False)
    op.create_index(op.f('ix_data_users_name'), 'data_users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_users_name'), table_name='data_users')
    op.drop_index(op.f('ix_data_users_last_name'), table_name='data_users')
    op.drop_index(op.f('ix_data_users_id'), table_name='data_users')
    op.drop_table('data_users')
    op.drop_index(op.f('ix_internal_users_username'), table_name='internal_users')
    op.drop_index(op.f('ix_internal_users_id'), table_name='internal_users')
    op.drop_index(op.f('ix_internal_users_email'), table_name='internal_users')
    op.drop_table('internal_users')
    # ### end Alembic commands ###
