"""Agregar parametros de creacion

Revision ID: dd13e7424681
Revises: 2316f394482a
Create Date: 2026-04-29 10:24:14.885102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd13e7424681'
down_revision: Union[str, None] = '2316f394482a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_users', sa.Column('id_user_create', sa.Integer(), nullable=True))
    
    op.execute("UPDATE internal_users SET id_user_create = 1 WHERE id_user_create IS NULL")
    
    op.alter_column('internal_users', 'id_user_create', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internal_users', 'id_user_create')
    # ### end Alembic commands ###
